In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
import warnings
from nltk.corpus import stopwords
from pathlib import Path
%matplotlib inline

warnings.filterwarnings('ignore')

## process train.csv

In [3]:
# process train.csv

import_path = 'raw/fake-news-FromKaggle/train.csv'
export_path = 'processed/fake-news-FromKaggle/train.csv'

In [4]:
# delete unnecessary data
df = pd.read_csv(import_path)
df = df.drop(columns=['id', 'title', 'author'], axis=1)
df = df.dropna(axis=0)
df['clean_news'] = df['text'].str.lower()
df['clean_news'] = df['clean_news'].str.replace('[^A-Za-z0-9\s]', '')
df['clean_news'] = df['clean_news'].str.replace('\n', '')
df['clean_news'] = df['clean_news'].str.replace('\s+', ' ')


# delete stopwords and punctuation
stop = stopwords.words('english')
df['clean_news'] = df['clean_news'].apply(lambda x: " ".join([word for word in x.split() if word not in stop]))


df

,text,label,clean_news
0,House Dem Aide: We Didn’t Even See Comey’s Let...,1,house dem aide didnt even see comeys letter ja...
1,Ever get the feeling your life circles the rou...,0,ever get feeling life circles roundabout rathe...
2,"Why the Truth Might Get You Fired October 29, ...",1,truth might get fired october 29 2016 tension ...
3,Videos 15 Civilians Killed In Single US Airstr...,1,videos 15 civilians killed single us airstrike...
4,Print \nAn Iranian woman has been sentenced to...,1,print iranian woman sentenced six years prison...
...,...,...,...
20795,Rapper T. I. unloaded on black celebrities who...,0,rapper unloaded black celebrities met donald t...
20796,When the Green Bay Packers lost to the Washing...,0,green bay packers lost washington redskins wee...
20797,The Macy’s of today grew from the union of sev...,0,macys today grew union several great names ame...
20798,"NATO, Russia To Hold Parallel Exercises In Bal...",1,nato russia hold parallel exercises balkans 11...
20799,"David Swanson is an author, activist, journa...",1,david swanson author activist journalist radio...

In [7]:
Path('processed/fake-news-FromKaggle').mkdir(parents=True, exist_ok=True)
df.to_csv(export_path, sep=',', index=False)

## process test.csv

In [15]:
# process test.csv

import_path1 = 'raw/fake-news-FromKaggle/test.csv'
import_path2 = 'raw/fake-news-FromKaggle/submit.csv'
export_path = 'processed/fake-news-FromKaggle/test.csv'

In [18]:
# delete unnecessary data
df = pd.read_csv(import_path1)
df2 = pd.read_csv(import_path2)
df = pd.merge(df, df2, on='id')

In [19]:

df = df.drop(columns=['id', 'title', 'author'], axis=1)
df = df.dropna(axis=0)
df['clean_news'] = df['text'].str.lower()
df['clean_news'] = df['clean_news'].str.replace('[^A-Za-z0-9\s]', '')
df['clean_news'] = df['clean_news'].str.replace('\n', '')
df['clean_news'] = df['clean_news'].str.replace('\s+', ' ')


# delete stopwords and punctuation
stop = stopwords.words('english')
df['clean_news'] = df['clean_news'].apply(lambda x: " ".join([word for word in x.split() if word not in stop]))


df

,text,label,clean_news
0,"PALO ALTO, Calif. — After years of scorning...",0,palo alto calif years scorning political proce...
1,Russian warships ready to strike terrorists ne...,1,russian warships ready strike terrorists near ...
2,Videos #NoDAPL: Native American Leaders Vow to...,0,videos nodapl native american leaders vow stay...
3,"If at first you don’t succeed, try a different...",1,first dont succeed try different sport tim teb...
4,42 mins ago 1 Views 0 Comments 0 Likes 'For th...,1,42 mins ago 1 views 0 comments 0 likes first t...
...,...,...,...
5195,Of all the dysfunctions that plague the world’...,0,dysfunctions plague worlds megacities none may...
5196,WASHINGTON — Gov. John Kasich of Ohio on Tu...,1,washington gov john kasich ohio tuesday signed...
5197,Good morning. (Want to get California Today by...,0,good morning want get california today email h...
5198,« Previous - Next » 300 US Marines To Be Deplo...,1,previous next 300 us marines deployed russian ...
5199,Perhaps you’ve seen the new TV series whose pi...,0,perhaps youve seen new tv series whose pilot e...

In [20]:
Path('processed/fake-news-FromKaggle').mkdir(parents=True, exist_ok=True)
df.to_csv(export_path, sep=',', index=False)